### ISSUE TITLE
Is this a duplicate addin

### ISSUE THREAD

**Issue by gep13** [NinetailLabs/Cake.PaketRestore#12]
I was just wondering if you had seen this addin, and associated module:

https://github.com/larzw/Cake.Paket

Is there a duplication of effort between these two packages?  Thanks!

/cc @larzw

**Comment by DeadlyEmbrace** [comment]
Seems like I had missed the addin the previous time I looked at Cake.Paket.
Mine works a little differently, but it is indeed a duplicate.

I'll mark it as deprecated with a link to Cake.Paket and unlist the packages from Nuget with a link as well

**Comment by gep13** [comment]
@DeadlyEmbrace thanks for getting back to me about this. That sounds like a good plan to me. Definitely worth reaching out to @larzw if there are things you still would like to see be added.

**Comment by larzw** [comment]
Hi!

I'm more than happy to accept PR's for stuff you think would be beneficial @DeadlyEmbrace. 

/cc @gep13

**Comment by gep13** [comment]
@DeadlyEmbrace I am going to go ahead and close this out.
